apiVersion: v2
name: ksnapshot
description: A Kubernetes operator that watches for annotated pods and creates CronJobs for database snapshots (MySQL, Elasticsearch, PostgreSQL) uploaded to S3
type: application
version: 0.3.0
appVersion: "0.3.0"
home: https://github.com/clickandmortar/ksnapshot
sources:
  - https://github.com/clickandmortar/ksnapshot
maintainers:
  - name: Click & Mortar
    url: https://github.com/clickandmortar
