{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ksnapshot.fullname" . }}
  labels:
    {{- include "ksnapshot.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - create
      - update
      - get
      - list
      - delete
  - apiGroups: [""]
    resources:
      - pods
      - services
    verbs:
      - get
      - list
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
{{- end }}
